Anpassungen fürs Magazin
JandBeyond/joomlade pull request #150
Opened 2017-03-07 10:49 UTC by drmenzelit

Titelfarbe im Bloglayout geändert
article-index angepasst

2017-03-07 11:13 UTC, zero-24 commented on src/templates/joomlade/css/editor.css
> + * joomlade v0.0.1 (http://www.joomla.de)
4 Mal der Header?

2017-03-07 11:20 UTC, drmenzelit commented on src/templates/joomlade/css/editor.css
> + * joomlade v0.0.1 (http://www.joomla.de)
wie meinst du? Kann nicht ganz folgen

2017-03-07 11:36 UTC, zero-24 commented on src/templates/joomlade/css/editor.css
> + * joomlade v0.0.1 (http://www.joomla.de)
in der Datei steht nun 4 mal das gleiche untereinander ;)
![image](https://cloud.githubusercontent.com/assets/2596554/23654780/a187604e-0332-11e7-929f-97e219659926.png)

2017-03-07 11:44 UTC, drmenzelit commented
wie ist das denn passiert? Die Datei habe ich eigentlich nicht angefasst

2017-03-07 13:26 UTC, dneukirchen commented on src/templates/joomlade/css/editor.css
> + * joomlade v0.0.1 (http://www.joomla.de)
Liegt am build tool des templates... 
Ist nicht deine schuld... 

Kannst einfach mal die duplicate löschen.

2017-03-08 11:38 UTC, drmenzelit commented
![magazin-mit-index-nachher](https://cloud.githubusercontent.com/assets/9153168/23702565/19e203e0-03fc-11e7-9cb4-fae2f15ec81f.png)
![magazin-mit-index-vorher](https://cloud.githubusercontent.com/assets/9153168/23702562/19e05248-03fc-11e7-82ed-41e924c5662a.png)
![magazin-blog-nachher](https://cloud.githubusercontent.com/assets/9153168/23702561/19e047b2-03fc-11e7-9e25-518c0bcf946e.png)
![magazin-blog-vorher](https://cloud.githubusercontent.com/assets/9153168/23702563/19e1358c-03fc-11e7-8f6a-38272bf8844d.png)
![interviews-nachher](https://cloud.githubusercontent.com/assets/9153168/23702564/19e1920c-03fc-11e7-99e3-087c9f3e057c.png)
![interviews-vorher](https://cloud.githubusercontent.com/assets/9153168/23702566/19e20282-03fc-11e7-8f05-a7bac86c354b.png)

2017-03-08 11:58 UTC, dneukirchen requested changes
Wie per glip besprochen: 

Bitte override interviews.php löschen und dafür mit css und .item-image.pull-left arbeiten.
Die bilder sollten dann in der richtigen größe eingefügt werden, was so oder so sinnvoll ist.

Vielen Lieben Dank! @drmenzelit 👍

2017-03-08 12:03 UTC, dneukirchen approved these changes

2017-03-08 12:03 UTC, merged